ADJECTIVES_1 = [
    "amber", "ancient", "azure", "bold", "bright", "calm", "cardinal", "cerulean",
    "cobalt", "copper", "coral", "crimson", "crystal", "curious", "drifting",
    "dusty", "ebony", "electric", "ember", "emerald", "faded", "falling", "fern",
    "fierce", "floating", "frozen", "gentle", "gilded", "glacial", "gleaming",
    "golden", "granite", "hollow", "humble", "indigo", "ivory", "jade", "keen",
    "lavender", "lazy", "lofty", "lone", "luminous", "misty", "moonlit", "mossy",
    "muted", "narrow", "nimble", "noble", "obsidian", "ochre", "opal", "pale",
    "patient", "pearl", "pebbled", "pewter", "pine", "polar", "proud", "quiet",
    "radiant", "ragged", "rapid", "regal", "remote", "rising", "roaming", "rocky",
    "rosy", "ruby", "russet", "rustic", "sage", "sandy", "sapphire", "scarlet",
    "scattered", "serene", "shadowed", "shining", "silent", "silver", "sleek",
    "slender", "slow", "smoky", "solar", "solemn", "stark", "stellar", "stony",
    "stormy", "subtle", "sunlit", "swift", "tawny", "teal", "tender", "twilight",
    "vast", "velvet", "verdant", "vivid", "wandering", "wild", "windswept", "wintry",
]

ADJECTIVES_2 = [
    "acorn", "alpine", "ancient", "birch", "blaze", "bloom", "blossom", "boulder",
    "brook", "canyon", "cedar", "cliff", "cloud", "comet", "coral", "crater",
    "creek", "crystal", "dawn", "delta", "dew", "dune", "dust", "eclipse",
    "ember", "fern", "fjord", "flint", "forest", "frost", "gale", "glade",
    "glacier", "glow", "gorge", "grove", "haven", "heath", "hollow", "horizon",
    "kelp", "lagoon", "lark", "lava", "lea", "ledge", "light", "loch",
    "lotus", "marsh", "meadow", "mist", "moon", "moraine", "moss", "nebula",
    "night", "oak", "orbit", "petal", "pine", "plain", "pond", "pool",
    "prism", "quartz", "rain", "reed", "reef", "ridge", "rift", "ripple",
    "river", "rock", "root", "sand", "sedge", "shadow", "shore", "snow",
    "solar", "spark", "spray", "spring", "star", "stone", "storm", "stream",
    "summit", "surf", "surge", "thorn", "tide", "timber", "tundra", "vale",
    "valley", "vapor", "veil", "vine", "void", "wave", "willow", "wind",
]

NOUNS = [
    "albatross", "antelope", "badger", "bear", "beetle", "bittern", "boar",
    "bobcat", "bunting", "capybara", "caracal", "cassowary", "cheetah", "chickadee",
    "chipmunk", "condor", "cormorant", "cougar", "coyote", "crane", "curlew",
    "darter", "deer", "dipper", "dormouse", "dove", "eagle", "egret", "falcon",
    "ferret", "finch", "flamingo", "fox", "frog", "gannet", "gecko", "gibbon",
    "goshawk", "grebe", "grosbeak", "grouse", "guillemot", "gull", "harrier",
    "hawk", "hedgehog", "heron", "hoopoe", "ibis", "jackal", "jaguar", "jay",
    "kingfisher", "kite", "kiwi", "lapwing", "lemur", "leopard", "linnet", "lion",
    "lizard", "loon", "lynx", "magpie", "marten", "merlin", "mink", "mongoose",
    "moorhen", "moose", "moth", "muskrat", "nightjar", "nuthatch", "ocelot",
    "osprey", "otter", "owl", "oystercatcher", "panda", "panther", "parrot",
    "partridge", "pelican", "penguin", "peregrine", "petrel", "pheasant", "pipit",
    "plover", "porcupine", "puffin", "quail", "rabbit", "raccoon", "rail", "raven",
    "redstart", "robin", "sandpiper", "serval", "shearwater", "shrike", "skunk",
    "skylark", "snipe", "sparrow", "starling", "stilt", "stoat", "stork", "swift",
    "tanager", "teal", "tern", "thrush", "tit", "toucan", "turaco", "vole",
    "vulture", "warbler", "waxwing", "weasel", "wheatear", "wolf", "wolverine",
    "woodcock", "woodpecker", "wren", "yellowthroat", "zebra",
]
